name: lint & build code
on:
  push:
    branches: [main]
  
jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: lint code
        run: yarn lint
      - name: build code
        run: yarn build
